### ISSUE TITLE
Add a --news option

### ISSUE THREAD

**Issue by gponcon** [Antiz96/arch-update#109]
Add the `--news` option, which simply allows you to view Arch Linux news.

**Comment by Antiz96** [comment]
Hi,

Excellent idea! That would also be a good way for people using the `NoNews` option to have a fast and easy method to check Arch news without having them being shown at each execution.

**Comment by Antiz96** [comment]
The `-n/--news` option has been added in #113 and will be included in the future `v1.12.0` release.

Thanks for the great suggestion :)
