### ISSUE TITLE
App shows lines that do not match any updates.

### ISSUE THREAD

**Issue by Giger22** [Antiz96/arch-update#136]
Hello, I use paru and I have an additional lines:
$ Paru -Sua
$ :: Looking for devel upgrades...
$ :: marked out of date: 
$ :: orphans: 
 there is nothing to do
[Image](https://i.imgur.com/m0rAMDG.png)

**Comment by Antiz96** [comment]
Hi,

This does not seem like `Arch-Update`, there's no such output in it.
Are you sure you're running this project?

**Comment by Giger22** [comment]
Sorry, I posted in the wrong repo.
