### ISSUE TITLE
Erreur de mise à jour flatpak

### ISSUE THREAD

**Issue by fadri14** [Antiz96/arch-update#137]
Salut, j'ai lancé la mise à jours et je me retrouve avec une erreur quand j'ai refusé la mise à jour des flatpaks.
```
Proceed with these changes to the user installation? [Y/n]: n
/usr/bin/arch-update : ligne 387 :  3154 Erreur de segmentation  (core dumped)flatpak update
```
Je donne juste l'information au cas où cela n'est pas volontaire

**Comment by Antiz96** [comment]
Hello, merci pour le rapport.

Ce n'est pas un problème au niveau d'Arch-Update mais au niveau de Flatpak:

![image](https://github.com/Antiz96/arch-update/assets/53110319/9fcc0e55-322c-44ce-9221-f0ad41cf3577)

Ce bug doit donc être traité au niveau de Flatpak directement, il n'y a rien que je ne puisse faire au niveau d'Arch-Update.
