### ISSUE TITLE
Make a proper systray applet for Arch-Update

### ISSUE THREAD

**Issue by Antiz96** [Antiz96/arch-update#146]
This has been requested quite a few times as it allows an easy integration within the system regardless of the panel/bar used by any DE/WM (as long as it has systray support, obviously).  

It is also way more elegant when it comes to dynamic icon changes (e.g. when there are pending available updates).
Indeed, the way this "dynamic icon changes" has been initially implemented on Arch-Update's side is *hacky* and do not even work properly for most people (see [this comment](https://github.com/Antiz96/arch-update/pull/145#issuecomment-2096960519)).

I'm still in favor of keeping the `.desktop` file anyway (for people that don't have/want a systray) but only using one single "regular/non-changing" icon (as most other applications do).

When it comes to the systray applet specs, here's what I could think of so far:
- Ideally written in a high-level, intelligible and widely used programing language (for instance Python or Rust).
- Can be launched by a systemd-service (or by running a simple command, such as `arch-update --applet` or `arch-update-applet`, that one can put in their autostart apps or WM config) to have it running at startup.
- For icons:
    - After a second thought, I'm not sure how relevant some icons are (e.g. the 'checking' and 'installing' icons) and how hard handling them in such an applet would be. So, if anything, we can eventually drop them and only have an "up to date" and an "update available" icons.
    - Depending on how hard it is to handle, having the applet showing the number of pending updates (such as what the [Arch Updates Indicator Gnome extension](https://extensions.gnome.org/extension/1010/archlinux-updates-indicator/) is doing) would be a nice plus!

To be honest, I don't have a precise idea on how to develop such an applet for now. I'm gonna start digging into it as soon as I'll be able to but, obviously, any help would be greatly appreciated! :smile:

**Comment by trigg** [comment]
Please assign me to this issue.

As attempting to switch to themeable icons breaks the use-case for installing to prefixes other than `/usr`, I'm rolling all the changes together so as to not introduce breaking intermediate changes.

I've already made a headstart on this.

**Comment by Antiz96** [comment]
> Please assign me to this issue.
>  [...]
> I've already made a headstart on this.

You rock! Thank you so much for the help on this, I appreciate it :slightly_smiling_face: 

> As attempting to switch to themeable icons breaks the use-case for installing to prefixes other than `/usr`, I'm rolling all the changes together so as to not introduce breaking intermediate changes.
> 

If anything, that's not that big of a deal. I actually don't think anyone is installing Arch-Update from source (or using some `-git` version of it somehow). As you may have seen, I linked this issue to a `v2.0.0`, so eventual breaking changes are expected here :)
On the `/usr` prefix matter, does using `/usr/local/share/icons/hicolor/` (with `hicolor-icon-theme` installed) would work? If not, we can force the `/usr` prefix for the icons in the Makefile if needed (since `hicolor-icon-theme` will become a dependency, ensuring that the `/usr/share/icons/hicolor/` path exists for everyone). 

For what it's worth, I think I would actually prefer the icon related changes (installing in hicolor theme and using icon names rather than paths) to be in a separate PR than the applet one, as I don't think there's a direct link between them. But if you already started putting everything together or if it adds any burden on your side for whatever reasons, let's just keep it as is :wink:

**Comment by trigg** [comment]
No problems. 

the new PR in will break icon changing for anyone using another prefix (just mentioning for the sake of anyone who might happen to find this later)

> So, if anything, we can eventually drop them and only have an "up to date" and an "update available" icons.

Now might also be a good time & place to mention there are generic icons in each icon theme, if we do feel like changing the icon set, I'd advise using icon named `software-update-available` and potentially hiding the icon when no updates are available.

**Comment by trigg** [comment]
> potentially hiding the icon

Or even making that a user preference.

**Comment by Antiz96** [comment]
> No problems.
> 
> the new PR in will break icon changing for anyone using another prefix (just mentioning for the sake of anyone who might happen to find this later)
> 
Only the icon changing right? The `.desktop` is still able to find the icon with only its name even if it is in `/usr/**local**/share/hicolor/scalable/apps/`? If so, that's fine. As written in this issue description, I'll drop the icon changing altogether anyway for the .desktop file. We'll handle that in the systray applet instead.

> > So, if anything, we can eventually drop them and only have an "up to date" and an "update available" icons.
> 
> Now might also be a good time & place to mention there are generic icons in each icon theme, if we do feel like changing the icon set, I'd advise using icon named `software-update-available` and potentially hiding the icon when no updates are available.

Can you elaborate on this? What exactly "hiding the icon" means in that context?
Anyway, I'm all in favor of every relevant changes we might have to do in that regard :)

**Comment by trigg** [comment]
>  The .desktop is still able to find the icon with only its name even if it is in /usr/**local**/share/hicolor/scalable/apps/

Yes. By default any panel should check both /usr and /usr/local prefixes for themed icons. The `cp` code will throw file-not-found errors for anyone following git and using a different prefix, but update will continue as usual.

> Can you elaborate on this? 

Sure. One proposal here (as a user preference) is not showing an 'up-to-date' icon at all and simply not having an icon show while 'up-to-date'. 

The other proposal is not to ship icons at all and use `software-update-available` which exists in icon themes already and enforce the above option (as there is no 'up-to-date' equivalent in default icons)

My apologies, I mixed two ideas into a very small space.

**Comment by Antiz96** [comment]
> Yes. By default any panel should check both /usr and /usr/local prefixes for themed icons. The `cp` code will throw file-not-found errors for anyone following git and using a different prefix, but update will continue as usual.
> 

Alright, thanks for the confirmation. As stated in https://github.com/Antiz96/arch-update/pull/147#issuecomment-2098282570, the `cp` error matter is actually not a problem as I will drop the "icon changing" part altogether in an incoming PR. I'm just waiting to have the time to work on it (probably later today) before merging #147 so we don't keep a breaking change for too long in the main branch.

> Sure. One proposal here (as a user preference) is not showing an 'up-to-date' icon at all and simply not having an icon show while 'up-to-date'.
> 
> The other proposal is not to ship icons at all and use `software-update-available` which exists in icon themes already and enforce the above option (as there is no 'up-to-date' equivalent in default icons)
> 
> My apologies, I mixed two ideas into a very small space.

Correct me if I'm wrong or if I misunderstood anything but, having an 'up-to-date' icon (and thus having the applet visible at any time) is interesting to:
1 - Having a simple way to make sure that the applet itself is running correctly.
2 - Being able to trigger an `arch-update` run at any time, either to force an update check or perform other actions (as Arch-Update does more than simply updating packages). *(I realized that it might not have been clear that `arch-update` should be ran when the systray applet is clicked, I'm adding that to the specs in the issue description).*

If I'm not wrong about the above, I would then prefer to have an 'up-to-date' icon to make sure the applet is visible (and usable) at any time.

As for using the `software-update-available` icon shipped by icon themes, I would still like Arch-Update to use its custom icon set (I should actually have someone contributing some new "personalized" icons for it soon-ish instead of the current "basic" ones!).
So we can have the "arch-update(.svg)" icon used by the applet as the 'up-to-date' icon and the "arch-update_updates-available(.svg)" when there are updates available. Is that fine?

**Comment by trigg** [comment]
> So we can have the "arch-update(.svg)" icon used by the applet as the 'up-to-date' icon and the "arch-update_updates-available(.svg)" when there are updates available. Is that fine?

Oh absolutely fine! I was putting the idea out simply as it might have lowered the maintenance burden on the project. 

> If I'm not wrong about the above, I would then prefer to have an 'up-to-date' icon to make sure the applet is visible (and usable) at any time.

Yeah that makes sense. I'm in this camp myself but I would anticipate feature requests to hide the icon could come up later.

Well we can deal with that when we deal with it.

For now I've put in the next step to systray integration. The statefile PR :)

**Comment by Antiz96** [comment]
https://github.com/Antiz96/arch-update/releases/tag/v2.0.0 :partying_face:
