### ISSUE TITLE
Tray should check all of XDG_DATA_DIRS and XDG_DATA_HOME for arch-update

### ISSUE THREAD

**Issue by trigg** [Antiz96/arch-update#151]
Presuming two prefixes isn't enough, ideally we would check for all the places the user has chosen to have `.desktop` files

(Assign me, for another day)

**Comment by Antiz96** [comment]
Actually... I found an *edgy* case where it would be interesting to look for `XDG_DATA_HOME` / `~/.local/share/applications`:
gio/glib2 has a *very* [limited list of supported terminals](https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gdesktopappinfo.c#L2694) by default.

People using another terminal emulator might want to modify the `.desktop` file (to "force" Arch-Update to launch with the said terminal), and put it in `XDG_DATA_HOME` / `~/.local/share/applications` (to avoid the modification being overwritten at each update). 

So indeed, having the systray looking for the following order would be great:
- $XDG_DATA_HOME/applications/arch-update.desktop
- $HOME/.local/share/applications/arch-update.desktop
- $XDG_DATA_DIRS/applications/arch-update.desktop
- /usr/local/share/applications/arch-update.desktop
- /usr/share/applications/arch-update.desktop

Base on the same logic currently applied [for the statefile](https://github.com/Antiz96/arch-update/blob/main/src/script/arch-update-tray.py#L15), I should be able to provide a PR for that :)

**Comment by Antiz96** [comment]
Actually... I found an *edgy* case where it would be interesting to look for `XDG_DATA_HOME` / `~/.local/share/applications`:
gio/glib2 has a *very* [limited list of supported terminals](https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gdesktopappinfo.c#L2694) by default.

People using another terminal emulator might want to modify the `.desktop` file (to "force" Arch-Update to launch with the said terminal), and put it in `XDG_DATA_HOME` / `~/.local/share/applications` (to avoid the modification being overwritten at each update). 

So indeed, having the systray looking for the following order would be great:
- $XDG_DATA_HOME/applications/arch-update.desktop
- $HOME/.local/share/applications/arch-update.desktop
- $XDG_DATA_DIRS/applications/arch-update.desktop
- /usr/local/share/applications/arch-update.desktop
- /usr/share/applications/arch-update.desktop

I guess we can use the same logic currently used [for the statefile](https://github.com/Antiz96/arch-update/blob/main/src/script/arch-update-tray.py#L15) :)
