### ISSUE TITLE
Add a right click menu to the systray applet to "quit/exit" it

### ISSUE THREAD

**Issue by Antiz96** [Antiz96/arch-update#163]
It would be great to have a right click menu for the systray applet to *gracefully* quit/close it (instead of requiring people to either manually stop the systemd service or killing the process when needing to re-launch the systray from the terminal to get some logs for instance).

That would ideally imply introducing the translation code so we can have the menu entries in multiple languages.

While we're at it, I guess an entry to actually launch arch-update in the said menu wouldn't hurt :)

**Comment by trigg** [comment]
I'm happy to be assigned this. I don't think it's necessary to give me any extra permission, I'm content to use pull requests 😀

**Comment by Antiz96** [comment]
> I'm happy to be assigned this. 

Thanks <3

> I don't think it's necessary to give me any extra permission, I'm content to use pull requests 😀

Well, actually you would need to use pull requests anyway as the main branch is protected :P
But up to you ;)

**Comment by DeN-AlB** [comment]
Great idea! :+1:
