### ISSUE TITLE
Unable to configure tray icon on Plasma

### ISSUE THREAD

**Issue by starscaledragon** [Antiz96/arch-update#201]
### Environment

- Distribution: Arch Linux
- Arch-Update version: 2.1.0

### Description of the bug

Tray icons on Plasma can be shown always besides other tray icons or can be shown on the tray icons popup (triggered by the arrow button shown in the picture).
![image](https://github.com/Antiz96/arch-update/assets/174369883/00132c23-7587-4087-b906-3183f897b287)

It seems that due to missing arguments on `QApplication` (at src/script/arch-update-tray.py), the Arch-Update tray icon can not be configured under Plasma.

### Screenshots / Logs

Current parameters: `QApplication([])`
![ARCH-BEFORE](https://github.com/Antiz96/arch-update/assets/174369883/0e1847ed-35c7-4483-9738-511c5818c927)

When setting up the first parameter, the icon issue is fixed and the first argument will be used as application title e.g. `QApplication(["Arch-Update"])`
![ARCH-AFTER](https://github.com/Antiz96/arch-update/assets/174369883/643be099-e1ca-4c25-8ac4-865dc98e9959)

**Comment by Antiz96** [comment]
Hi,

Thanks a lot for the detailed report! :pray: 

I am planning on releasing [v2.2.0](https://github.com/Antiz96/arch-update/milestone/13) later today, it would be great to include this trivial fix in it! :smile: 

Would you be willing to open a pull request for it?  
If not, I can just commit it myself. It's up to you :wink: 

In any case, thanks once again!

**Comment by starscaledragon** [comment]
PR created :)

**Comment by Antiz96** [comment]
> PR created :)

Merged ;)

As I said, I'm planning on releasing [v2.2.0](https://github.com/Antiz96/arch-update/milestone/13) later today, including this fix.

Thanks once again for the bug report and the PR!
