### ISSUE TITLE
Integrating in plasma systray 

### ISSUE THREAD

**Issue by Xdavius** [Antiz96/arch-update#21]
Sorry to write here, but you don't explain on how I must do to make the integration in the plasma systray (or gnome systray, but I use plasma )

Can you give me the process please?

It will be great adding the process in the readme for everyone.

It's hard to find this information.

Thanks a lot.

**Comment by Antiz96** [comment]
Hi @Xdavius

`arch-update` can't be integrated into the systray directly, at least not in its current form.

However, `arch-update` is no more than a regular application that you should be able to integrate anywhere else (such as your desktop, your dock, your panel's launcher, etc...) just like you would do with `firefox` or `discord` shortcuts (for example).

For instance, one could add `arch-update` between `firefox` and `discover` in the bottom panel/bar in the below image:
![image](https://user-images.githubusercontent.com/53110319/219319039-2316ad5c-d64b-406c-98ac-cb817418dcb4.png)

Or it can be integrated into your `latte` dock (if you use that), `dash to dock/dash to panel` (for Gnome users) or any other dock really. Just like I did on IceWM back when I was using it:
![image](https://user-images.githubusercontent.com/53110319/219320439-4e05b51f-2cc4-44aa-b882-94701df5dfb0.png)

If your bar supports adding custom launcher, you can add it there as well. This is what I did with `tint2` on `i3` (it looks like it's in the systray but it's not, it's actually next to it. It's basically an app launcher in which I can put any app shortcut):

![image](https://user-images.githubusercontent.com/53110319/219321417-b5406663-7a0f-4502-9661-1242bf357830.png)

 The `arch-update` shortcut can be found in your app menu or under `/usr/share/applications/arch-update.desktop` (if you installed it from source and not via the AUR, then it's: `/usr/local/share/applications/arch-update.desktop`).

So you cannot integrate it in your systray but you can integrate it pretty much anywhere else.
I hope this helps. Tell me if you need more precision :)

**Comment by Antiz96** [comment]
@Xdavius Can I close this issue or you need more information?

**Comment by Antiz96** [comment]
Without answers from you, allow me to close this issue.

**Comment by Antiz96** [comment]
Hi,

Sorry for *necro-bumping* this issue, but I just wanted to let you know (as well as everyone passing by) that Arch-Update now has a proper systray applet that automatically fits and runs properly in the KDE systray!

After updating to Arch-Update [v2.0.0](https://github.com/Antiz96/arch-update/releases/tag/v2.0.0), you can remove the `.desktop` icon from your panel and start the systray applet instead, like so:
`systemctl --user enable --now arch-update-tray.service`
