### ISSUE TITLE
Propose to reboot before proposing restarting the services

### ISSUE THREAD

**Issue by Temet79** [Antiz96/arch-update#224]
Hi,

If an upgrade proposes both to restart services and to reboot, I think the order should be inverted for the reason below.

When I'm asked to restart the services, I say "yes".
Then I'm asked if I want to reboot (because of a kernel update) ... so restarting the services was useless.

If you propose first to reboot :
- if say yes, then don't propose to restart the services and start the reboot
- if say no, then propose to restart the services.

Regards,

David

**Comment by Antiz96** [comment]
Hi,

Thanks for the feature request! That sounds like a reasonable change, indeed :)

Would you be up to open a pull request for it? It should be as easy as inverting lines [797 & 798](https://github.com/Antiz96/arch-update/blob/main/src/script/arch-update.sh#L797-L798) in the `src/script/arch-update.sh` file.

**Comment by Temet79** [comment]
Hi,

Thanks.
Let me search and try to figure out how to do a pull request... I'm curious about the process but I don't know how to do it.
If I don't figure out how to do it... I'll update.

Regards,

David

**Comment by Temet79** [comment]
I did "something"... was a lot of efforts to invert 2 lines :)

I hope I did it right...  please don't hesitate to give some pieces of advice otherwise.

**Comment by Antiz96** [comment]
Thanks! It looks good at first glance :)

I'm not home right now, I'll test/merge it as soon as I can ;)

**Comment by Antiz96** [comment]
Change included in [v2.3.2](https://github.com/Antiz96/arch-update/releases/tag/v2.3.2). 
Thanks again for your contribution!
