### ISSUE TITLE
Dark Tray Icon

### ISSUE THREAD

**Issue by hunabku94** [Antiz96/arch-update#240]
### Description

Tray icon is barely visible when using a light theme.

### Motivation and context

I use a light theme, and the light tray icon is barely visible. So, can you add a toogle to use Dark/Light please ?
Thanks a lot!

**Comment by hunabku94** [comment]
![arch-update](https://github.com/user-attachments/assets/c151336c-ab9e-49f9-899e-99182d94a7e8)
![arch-update_updates-available](https://github.com/user-attachments/assets/25cdb068-0850-43eb-812a-4548f0ba6f6d)

**Comment by hunabku94** [comment]
I make this too for my usage. Maybe be useful.

**Comment by Antiz96** [comment]
Hi,

Thanks for the feature request!
Interesting one :)

We made the red circle on new updates specifically to be visible even on light theme, but I understand the use case for dark tray icons.

Having a toggle button to switch between the "classic/light" icons set and a "dark" one might not be as easy to implement as it sounds. I'm afraid it would add too much complexity to be worth it. 
However, I should be able to add an option for that in the `arch-update.conf` configuration file (e.g. `TrayIconStyle=dark`). How does that sounds?

**Comment by Antiz96** [comment]
Also, are you interested in opening a pull request to add the dark icons set?

If should be as easy as copying the two `svg` files [here](https://github.com/Antiz96/arch-update/tree/main/src/icons) with a `-dark` suffix ("arch-update-dark.svg" & "arch-update_updates-available-dark.svg") and change the value of the [`fill` variable](https://github.com/Antiz96/arch-update/blob/main/src/icons/arch-update.svg?short_path=1503cf4#L6) to "000000".

**Comment by Antiz96** [comment]
Thanks again for the cool feature request and the related pull request!  
I'll release `v3.1.0` in a few, including the dark and blue systray icon variants :wink: 

If anyone passing by is interested to contribute new additional style/color variants for the systray icon, it should now be relatively easy to do! I described the steps [here](https://github.com/Antiz96/arch-update/pull/242#issuecomment-2374810590) :art:
