### ISSUE TITLE
No icon graphics available in Gnome overview?

### ISSUE THREAD

**Issue by DeN-AlB** [Antiz96/arch-update#261]
### Environment

- Distribution: EndeavourOS Gnome
- Arch-Update version: 3.2.0 from AUR

### Arch-Update configuration

No arch-update.conf configuration file in use.

### Description of the bug

I'm using EndeavourOS with Gnome desktop. I was wondering that there are no icon graphics shown in the overview for arch-update. Only the default icons are shown.

![image](https://github.com/user-attachments/assets/50e2bb45-a565-4cb8-8e9d-15299aa6af94)

I tried removing and reinstalling arch-update, but icons are still not available.

What can I do to get the icon graphics back?

**Comment by Antiz96** [comment]
Hi,

Thanks for the report!

This is a bug introduced in Arch-Update `v.3.1.0`, it seems like I forgot to update the desktop files to reflect the new icon names. This will be fixed in the next Arch-Update release (`v3.2.1`) :)

**Comment by Antiz96** [comment]
Fixed in https://github.com/Antiz96/arch-update/pull/263, I'll release `v3.2.1` soon-ish.

Thanks again for the report!

**Comment by DeN-AlB** [comment]
Great! Thanks for the quick response and the upcoming fix. :+1:
