### ISSUE TITLE
pas icone a arch-update sur gnome 47

### ISSUE THREAD

**Issue by lio-rega** [Antiz96/arch-update#265]
Bonjour 

je suis sur Archlinux  et depuis que jai mis a jour gnome 47 j'ai pas icon  j'ai une roue dentellé comme icone pour application arch-update 

jai essayer de chercher rien trouvé

merci de votre aide

**Comment by Antiz96** [comment]
Bonjour,

De quelle icône parlez vous ?

S'il s'agit de l'icône dans le menu d'application, c'est un bug connu qui sera corrigé dans la nouvelle version d'Arch-Update (qui devrait sortir ce soir). Voir https://github.com/Antiz96/arch-update/issues/261

S'il s'agit de l'icône "systray" dans la barre des tâches, il faut la démarrer. Je vous renvoi à cette section de la documentation qui devrait vous fournir toutes les infos nécessaires : https://github.com/Antiz96/arch-update/blob/main/README-fr.md#lapplet-systray
Il est important de noter que Gnome ne supporte pas les icônes systray par défaut. Pour cela, il faut installer et démarrer l'extension suivante : https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by lio-rega** [comment]
merci et dsl du dérangement jai pas encore abitude je suis asser novice sur github.com pour rechercher

S'il s'agit de l'icône dans le menu d'application, c'est un bug connu qui sera corrigé dans la nouvelle version d'Arch-Update (qui devrait sortir ce soir). Voir https://github.com/Antiz96/arch-update/issues/261.

merci beaucoup 
bonne soiré

**Comment by Antiz96** [comment]
Aucun souci, merci tout de même pour le rapport de bug !
