### ISSUE TITLE
Qt may start before XDG

### ISSUE THREAD

**Issue by Delor3an91** [Antiz96/arch-update#269]
### Environment

Manjaro XFCE
The Arch-Update version can be retrieved by running `arch-update --version` --> 3.2.2

- Distribution: Manjaro
- Arch-Update version: 3.2.2

### Description of the bug

Qt availability priority may start before XDG one (when XDG is available on the system).
After login in the user session, when Arch-Update systray is launched through the actual and default /home/${USER}/.config/arch-update-tray.desktop --> arch-update --tray
it may launched with Qt UI instead of XDG one.

A workaround for that is to add a sleep timer to the Exec of that .desktop file who look like that:

Exec=sh -c "sleep 10 && (arch-update --tray &)"

Maybe 10 seconds wait for launch is too much and can be reduced but it do the trick.

Wish You well

**Comment by Antiz96** [comment]
Hi,

Thanks for the report!

As you said, this issue *may* occur but it only seems to happen in rare / specific situations. For instance, I didn't had any reports for this before and I cannot reproduce it on my Arch XFCE test environment (but I already faced this issue with other applications and / or in a different environment, so I'm aware it can be a thing :sweat_smile:).  
Also, for what it's worth, this is not an issue with Arch-Update itself per say.

As such, I'm not willing to add a `sleep` timer by default in the desktop file. However, I think it's fair to document it in the documentation (e.g. READMEs and man pages) so people can easily find the workaround if needed.

I'll add that to the documentation soon.
