### ISSUE TITLE
Support for pikaur 

### ISSUE THREAD

**Issue by t-animal** [Antiz96/arch-update#275]
### Description

Support for pikaur as an additional aur pacman wrapper.

### Motivation and context

AUR wrappers show diffs to the last installed version of the installation scripts when installing a new version. This is critical for security. When arch-update uses a different package manager than what the user uses otherwise, these updates becomes misaligned. I don't know if it is feasible to just support all wrappers [that there are](https://wiki.archlinux.org/title/AUR_helpers#Comparison_tables), but I for one use pikaur and hope that it could be added as a supported wrapper. I _guess_, that if they're compatible with pacman, adding them should be relatively easy.

Maybe a more generic option could also be viable. Like setting a path to a wrapper in the config file instead of naming the wrapper.

**Comment by Antiz96** [comment]
Hi,

Thanks a lot for the feature request!

> AUR wrappers show diffs to the last installed version of the installation scripts when installing a new version. This is critical for security. When arch-update uses a different package manager than what the user uses otherwise, these updates becomes misaligned.

This is a fair point! However...

> I don't know if it is feasible to just support all wrappers [that there are](https://wiki.archlinux.org/title/AUR_helpers#Comparison_tables),

...it's definitely not feasible to support every AUR helpers / pacman wrapper there is.

> but I for one use pikaur and hope that it could be added as a supported wrapper. I guess, that if they're compatible with pacman, adding them should be relatively easy.

It's indeed important that they share options with pacman itself (to easy their support integration within `Arch-Update`) but, most importantly, they should also be compatible with each other in terms of options, to avoid complicating the different scripts / libraries with numerous conditionals statements.

Luckily, it seems like `pikaur` shares most options with `yay` and `paru` (at least the ones we are interested in for `Arch-Update`, at first glance).
I still need to study that deeper and make some tests before confirming if `pikaur` support could be added or not though.

I have a lot to do in the incoming days / weeks, so I can't promise I'll be able to do that soon, but I'll try my best!
I'll let you know :wink:

**Comment by Antiz96** [comment]
Turns out I got time to make a few quick tests today and adding support for `pikaur` *should* be doable!

I'm starting to work on this.
Thanks again for the feature request :)

**Comment by Antiz96** [comment]
Support for `pikaur` added in https://github.com/Antiz96/arch-update/pull/276, included in the [`v3.4.0` release](https://github.com/Antiz96/arch-update/releases/tag/v3.4.0) :wink:
