### ISSUE TITLE
False Positive on Unused Flatpak Packages for Pinned Runtimes

### ISSUE THREAD

**Issue by RayJW** [Antiz96/arch-update#285]
### Environment

- Distribution: CachyOS
- Arch-Update version: 3.4.1

### Description of the bug

When running `arch-update` and Flatpak has pinned runtimes, it reports that there are unused runtimes, even if there are none. 

### Screenshots / Logs

```text
==> Flatpak Unused Packages:
runtimes

-> Would you like to remove this Flatpak unused package now? [y/N] y

==> Removing Flatpak Unused Packages...

These runtimes in installation 'user' are pinned and won't be removed; see flatpak-pin(1):
  runtime/org.freedesktop.Sdk.Extension.freepascal/x86_64/24.08
  runtime/org.kde.Sdk/x86_64/6.8
Nothing unused to uninstall
```

### Additional context

I suspect that this is merely due to the way the output of `flatpak uninstall --unused` output is parsed.

**Comment by Antiz96** [comment]
Hi,

Thanks for the bug report!
This is indeed most likely an issue with the output parsing. I had [a similar issue](https://github.com/Antiz96/arch-update/issues/103) in the past already. Unfortunately the flatpak CLI output is a bit difficult to work with :disappointed: 

I'll investigate and try to come up with a fix soon.
I'll let you know :)

**Comment by RayJW** [comment]
> This is indeed most likely an issue with the output parsing. I had [a similar issue](https://github.com/Antiz96/arch-update/issues/103) in the past already. Unfortunately the flatpak CLI output is a bit difficult to work with 😞

Yea, I've been there. I hope some day we get https://github.com/flatpak/flatpak/issues/5499, that would make things easier ^^'

**Comment by Antiz96** [comment]
> > This is indeed most likely an issue with the output parsing. I had [a similar issue](https://github.com/Antiz96/arch-update/issues/103) in the past already. Unfortunately the flatpak CLI output is a bit difficult to work with 😞
> 
> Yea, I've been there. I hope some day we get [flatpak/flatpak#5499](https://github.com/flatpak/flatpak/issues/5499), that would make things easier ^^'

Oh wow, I wasn't aware of this feature request, thanks for sharing!
Definite +1 for me! :D

**Comment by Antiz96** [comment]
Turns out this can be fixed with the same mechanism I used in https://github.com/Antiz96/arch-update/pull/104 to fix the similar issue there was with `flatpak update`.

In practice, that means modifying the following line in the [orphan_packages.sh](https://github.com/Antiz96/arch-update/blob/main/src/lib/orphan_packages.sh#L10) lib script like so (addition of the `sed -n '/^ 1./,$p'` part before the `awk`):

- before: `flatpak_unused=$(flatpak remove --unused | awk '{print $2}' | grep -v '^$' | sed '$d')`
- after: `flatpak_unused=$(flatpak remove --unused | sed -n '/^ 1./,$p' | awk '{print $2}' | grep -v '^$' | sed '$d')`

Would you be interested in contributing that fix via a pull request?

**Comment by Antiz96** [comment]
@RayJW Thanks a lot, that's really appreciated. While you're at it, do you mind replacing `flatpak remove` by `flatpak uninstall` in that line as well? :D

`remove` seems to [only be an alias](https://github.com/flatpak/flatpak/blob/ff8490a91e3c6d9e8ff146e76a5b30ccaf22fdf0/app/flatpak-main.c#L82-L83) for the actual `uninstall` command, so better use the latter I guess :)

**Comment by RayJW** [comment]
> @RayJW Thanks a lot, that's really appreciated! While you're at it, do you mind replacing `flatpak remove` by `flatpak uninstall` in that line as well? :D
> 
> `remove` seems to [only be an alias](https://github.com/flatpak/flatpak/blob/ff8490a91e3c6d9e8ff146e76a5b30ccaf22fdf0/app/flatpak-main.c#L82-L83) for the actual `uninstall` command, so better use the latter I guess :)

Whoops, jumped the gun there. Sure, I'll add a commit for that real quick :)

**Comment by Antiz96** [comment]
There is still another opened issue I'd like to be dealt with before tagging a new release. Another person was interested in opening a PR for it soon-ish.

I will patch the Arch-Update AUR package to include this fix right now though, so you don't have to wait for the next release to enjoy the fix (assuming you use the AUR package) :)

**Comment by Antiz96** [comment]
AUR package [patched](https://aur.archlinux.org/cgit/aur.git/commit/?h=arch-update&id=b81a627c963f730b7e157b1901be67ae57910ab0) ;)
Thanks once again!
