### ISSUE TITLE
Rust

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [Antiz96/arch-update#79]
Est il possible de mettre à jour mes app Rust cargo aussi avec ?

**Comment by Antiz96** [comment]
Hello,

A l'exception de Flatpak (et de `yay`/`paru` pour la prise en charge du AUR), Arch Update n'a pas été conçu pour prendre en compte les packages managers "alternatifs" (type `cargo`, `pip(x)`, `gem`, etc...).

Il n'est donc pas possible de mettre à jour ses app Rust avec cargo directement via Arch Update.
En revanche, si une application Rust a été installée depuis le AUR, la mise à jour de cette dernière sera prise en charge.
