### ISSUE TITLE
Refaire l'interface avec Gum cli

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [Antiz96/arch-update#85]
Bonjour, serait il possible d'empêcher le prompt des news ? Et si c'est possible d'utiliser Gum cli pour l'interface?

https://github.com/charmbracelet/gum
Ça rendrait le script plus beau.

Serait il possible s'il y a une update d'ouvrir automatiquement le terminal pour mettre le mot de passe directement sans tout ces Yes yes yes yes.

**Comment by Antiz96** [comment]
Hello,

Pour ce qui est d'utiliser Gum cli pour l'interface, ce n'est pas prévu.
Je préfère ne pas complexifier le script pour "si peu", il a plutôt pour vocation d'être simple et efficace que "beau".

En revanche, pour ce qui est du prompt des news, je peux le rendre optionnel.
Il est conseillé de vérifier les news régulièrement, mais je conçoit que certains puisse vouloir sauter cette étape dans `Arch Update`.
Je suis en train de travailler sur un fichier de configuration pour `Arch Update` qui permettra d'activer/désactiver certaines options (voir #83). 
Bien que je ne recommanderai pas personnellement son utilisation, je peux ajouter une option `nonews` dans ce fichier de configuration permettant d'empêcher le prompt des news. Merci pour la suggestion :)

Pour ce qui est de demander directement le mot de passe sans aucune forme de confirmation, je ne suis pas sûr de comprendre...
Le mot de passe est demandé après avoir accepté d'appliquer les mises à jour et avoir passé le prompt des news, soit après avoir appuyé deux fois sur touch "Entrée" (ou une fois si vous utilisez la future option permettant d'empêcher le prompt des news), et il ne devrait plus être redemandé par la suite *(sauf en cas de mise à jour très longue qui dépasserait le timeout de `sudo`, le forçant à vous redemander le mot de passe. Mais si c'est le cas et que ça vous ennuie, c'est un paramètre à gérer directement via la configuration de `sudo`, c'est hors du scope d'`Arch Update`)*.
Si c'est à propos des questions de confirmation posées par le script à chaque étape (yes?/no?), il me parait primordiale pour le script de laisser à l'utilisateur le temps d'analyser la liste des paquets/fichiers concernées par chaque étape et d'explicitement laisser l'utilisateur accepter (ou refuser) de porter l'action liée.

Quoi qu'il en soit, je ne suis pas pour l'ajout d'une option "d'auto-confirmation" (si c'est bien de ça qu'il s'agit). Le but de ce script est justement de présenter les informations utiles et importantes à l'utilisateur pour qu'il puisse ensuite décider de quoi faire, tout en l'accompagnant.
Si quelqu'un souhaite simplement mettre son système à jour sans avoir d'informations qui lui sont présentés et sans avoir à répondre à diverses questions de confirmations, alors nul intérêt d'utiliser un script tel que `Arch Update`.
Un simple alias du type `sudo pacman -Syu --noconfirm && paru -Syu --noconfirm && yes | flatpak update && pacman -Qtdq | sudo pacman -Rns --noconfirm - && [...]` fera l'affaire (inutile de préciser qu'une telle pratique est évident déconseillé).

**Comment by Antiz96** [comment]
J'ai rajouté l'option `nonews` dans le ticket lié à la mise en place du fichier de configuration (#83).
Je travaillerai dessus prochainement. 

En revanche, je pense que j'ajouterai un message de warning lorsque cette option sera utilisée pour bien signifier qu'il est recommandé de vérifier régulièrement les news avant de mettre à jour son système. Le message ne nécessitera pas de confirmation de lecture ou quoi que ce soit, donc l'effet escompté sera le même (le prompt des news ne sera pas affiché sans une quelconque confirmation de la part de l'utilisateur) mais cela permettra aux utilisateurs d'être avertie des bonnes pratiques.

**Comment by Antiz96** [comment]
L'ajout de couleur au retour du script pour une meilleure lisibilité a été instauré via https://github.com/Antiz96/arch-update/pull/87/commits/23d439cf5a3f744b3d61aefc901f75dfa845ed9a

L'ajout de l'option "NoNews" via le fichier de configuration a été ajouté via https://github.com/Antiz96/arch-update/pull/89/commits/4e17c49110f80828e3078971040d2b94ec7739c2

Ces nouveautés seront disponible dans `v1.10.0` qui devrait sortir prochainement.

**Comment by jojojojojoj5564656465465** [comment]
Peux tu gérer l'ajout de vim lors de l'installation car je ne l'avais pas et ça bugait pour voir la diff de deux fichiers

Ne penses-tu pas faire du NoNews:false par default dans la config ?

**Comment by Antiz96** [comment]
> Peux tu gérer l'ajout de vim lors de l'installation car je ne l'avais pas et ça bugait pour voir la diff de deux fichiers
> 
vim est déjà noté comme dépendance optionnelle d'Arch-Update en tant que "programme de diff/merge par défaut pour pacdiff" (voir le [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=arch-update#n15) et la partie ["Description" du README](https://github.com/Antiz96/arch-update#description) qui le mentionnent). 
Il est cependant possible d'utiliser autre chose que vim pour ceux qui le souhaitent (comme expliqué [ici](https://wiki.archlinux.org/title/Pacman/Pacnew_and_Pacsave#pacdiff)), d'où le fait que ce ne soit qu'une dépendance optionnelle et pas obligatoire.

> Ne penses-tu pas faire du NoNews:false par default dans la config ?

Comme expliqué [ici](https://wiki.archlinux.org/title/System_maintenance#Read_before_upgrading_the_system), les utilisateurs sont encouragés à vérifier régulièrement les news avant de mettre à jour leur système. En effet, il est recommandé de vérifier les news avant chaque mise à jour du système afin d'être au courant des éventuelles interventions manuelles nécessaires avant/après mise à jour. 
L'affichage des news est une des fonctionnalité principale d'Arch-Update, il n'est donc pas prévu de la désactiver par défaut.
Ceux qui souhaitent vraiment désactiver cette fonctionnalité peuvent utiliser l'option "NoNews" dans le fichier `arch-update.conf` (voir documentation [ici](https://github.com/Antiz96/arch-update#arch-update-configuration-file))

**Comment by Antiz96** [comment]
Hello,

Pour information, l'option `NoNews` dans `arch-update.conf` sera dépréciée et totalement supprimée à la sortie de la prochaine version `v1.12.0` (qui devrait sortir sous peu) au profit d'un nouveau comportement par défaut pour l'affichage des news.

En effet, à partir de la `v1.12.0` les news ne seront affichées que lorsqu'au moins une nouvelle news aura été publiée depuis la dernière exécution d'`Arch-Update` afin d'introduire un affichage des news plus pertinent et éviter d'avoir systématiquement les mêmes news affichées en permanence. Les news publiées depuis la dernière exécution d'`Arch-Update` seront étiquetées comme '[NEW]/[NOUVEAU]'.

Avec un tel comportement, les news ne seront affichées que rarement et uniquement lorsque que c'est pertinent. Je ne vois donc plus d'intérêt à l'option `NoNews` en l'état et est donc décidé de la supprimer complètement.
La prise en charge de l'affichage des news est une fonction clef d'`Arch-Update`, il me semble plus intéressant de travailler sur un affichage plus pertinent de ces dernières que de simplement permettre de les cacher/supprimer en réponse à un affichage non cohérent.

Pour ce que ça vaut, la `v1.12.0` introduira également une nouvelle option `arch-update -n\--news` pour pouvoir afficher les news à tout moment et l'option `AlwaysShowNews` pour `arch-update.conf` afin de retrouver "l'ancien" comportement (toujours afficher les Arch news avant de mettre à jour, peu importe s'il y en a une nouvelle depuis la dernière exécution ou non).
