### ISSUE TITLE
French translation for arch-update

### ISSUE THREAD

**Issue by jfchadeyron** [Antiz96/arch-update#93]
Can i help you to have arch-update in french ?
Thanks.

**Comment by Antiz96** [comment]
Hello,

With pleasure! 
I could have done it earlier, but right now I don't have the time (nor the courage) to do it all by myself.  :sweat_smile:

Ideally, everything should be translated (meaning not only the script itself but also the man pages and the README), but the effort has to start somewhere! :smile:

- For the script itself, we can use a `po` file in `arch-update/po/fr.po`. See the one from [paru](https://github.com/Morganamilo/paru/blob/master/po/fr.po) for instance.
- For the man pages we can create translated versions in `arch-update/doc/man/fr/{arch-update.1,arch-update.conf.5}` that I'll ship to users via the Makefile.
- For the README, we can create a translated `README-fr.md` file and make a link back and forth between the regular `README.md` english file and the french one.

Anyway, I would be glad to have some help on that matter! :pray: 

I created a ["fr-translation"](https://github.com/Antiz96/arch-update/tree/fr-translation) branch, feel free to some make pull requests against it to start the effort and contribute to the french translation :)
The above goes for everybody passing by that wish to help ! :angel: :smile:

**Comment by jfchadeyron** [comment]
Ok finished pour README.md.
You can check this : https://github.com/jfchadeyron/arch-update/tree/main

**Comment by Antiz96** [comment]
Nice, thanks a lot!

Can you open a pull request against the `fr-translation` branch? That would be the easiest way to check, discuss and merge your changes together :)

**Comment by jfchadeyron** [comment]
Of course, sorry. It's done.

**Comment by Antiz96** [comment]
Is it? I can't see it :p

**Comment by Antiz96** [comment]
README done in #95 (thanks again for your help @jfchadeyron).

**Comment by Antiz96** [comment]
Added a checklist in [that comment](https://github.com/Antiz96/arch-update/issues/93#issuecomment-1881156629) to track progress.

**Comment by Antiz96** [comment]
I created a copy of the man pages in `doc/man/fr/` in the `fr-translation` branch [here](https://github.com/Antiz96/arch-update/tree/fr-translation/doc/man/fr).
It should be fairly quick and easy to translate as most of the content can (and should) be copied/pasted from the [french README](https://github.com/Antiz96/arch-update/blob/fr-translation/README-fr.md).

If anyone wants to start contributing to translating them, feel free to open a pull request.
Otherwise I'll just start translating them on my side as soon as I'll be able to do so :)

**Comment by Antiz96** [comment]
I made the french versions of the man pages and added them to the Makefile so systems set up with a french locale variant as their language will use those french versions by default.

All of this as well as the french version of the README have been merged into the `main` branch in https://github.com/Antiz96/arch-update/pull/102.

I'll create the necessary files to start working on the translation of the script and push them to the `fr-translation` branch as soon as I can. It might take a bit of time as I also have to make some modifications to the script itself to make it compliant with the future translation (and I'm also a bit busy these days :sweat_smile:).
I'll leave a message on that issue once those files are created in case someone is interested in contributing to translating the script :slightly_smiling_face:.

**Comment by Antiz96** [comment]
I created the necessary files to start translating `Arch-Update` *(which are hopefully correct and complete...)* and pushed them to the [fr-translation branch](https://github.com/Antiz96/arch-update/tree/fr-translation/po), including [the one for the french translation](https://github.com/Antiz96/arch-update/blob/fr-translation/po/fr.po).

I'll start working on the french translation of the script this weekend (unless someone else started the effort by then :eyes: :smile:).

**Comment by Antiz96** [comment]
I opened the #107 PR that brings the french translation for the `Arch-Update` script itself.
Once reviewed and merged, we can consider the translation complete and close that issue.

I will release `v1.11.0` including the french translation soon*-ish*.

**Comment by Antiz96** [comment]
French translation reviewed and merged. I'll tag a new release in a minute! :)

**Comment by Antiz96** [comment]
[`v1.11.0`](https://github.com/Antiz96/arch-update/releases/tag/v1.11.0) has been released, including complete french translation :)
