### ISSUE TITLE
override.conf does not work anymore ?

### ISSUE THREAD

**Issue by Saroumane** [Antiz96/arch-update#96]
Since release 1.10.0 of arch-update, it seems my `~/.config/systemd/user/arch-update.timer.d/override.conf` which contains : 

```
[Timer]
OnUnitActiveSec=1d
```

is ignored by arch-update (which runs every hour, like defined in `~/.config/systemd/user/timers.target.wants/arch-update.timer` )

**Comment by Antiz96** [comment]
Hi,

Sorry, that's a miss in the documentation. 
The correct content of you `override.conf` file should be:

```
[Timer]
OnUnitActiveSec=
OnUnitActiveSec=1d
```

This is because systemd timer can actually take multiple `OnUnitActiveSec=` parameters.
So by providing an `override.conf` file like the one you currently have, you're actually **adding** the `OnUnitActiveSec=1d` parameter to the already existing existing one (`OnUnitActiveSec=1h`).

As documented in the [`systemd.timer` man page](https://www.freedesktop.org/software/systemd/man/latest/systemd.timer.html), you first need to assign an empty string to the `OnUnitActiveSec` parameter in your `override.conf` file to reset the list of any existing iteration of that timer parameter, and then to declare your own parameter in order for it to act as a complete replacement (and not an addition to any existing timer parameters):

![image](https://github.com/Antiz96/arch-update/assets/53110319/ae8e63f2-58d2-45ce-94e2-15fb3844ef43)

I'll correct the `arch-update` documentation (README and man page) in a min and make a bugfix release for it.
Thanks for the report!

**Comment by Saroumane** [comment]
Thanks for the explanation. Now I remember I previously edited directly the `arch-update.timer` without using any override file.

**Comment by Antiz96** [comment]
> Thanks for the explanation. Now I remember I previously edited directly the `arch-update.timer` without using any override file.

Yeah, this explains that. 
This is actually how I documented that at first (editing the `arch-update.timer` directly) but now I recommend to use an override file instead (which is the actual proper way to make changes to a systemd service/timer unit file).
It avoid modifying the "main" unit file (and risking to break it) and it also allow your changes to persist between updates (because changes made to the "main" unit file will be overwritten at the next `arch-update` update).

**Comment by Antiz96** [comment]
Documentation corrected and included in the new [v1.10.1 bugfix release](https://github.com/Antiz96/arch-update/releases/tag/v1.10.1).
Thanks once again for the report!

**Comment by Saroumane** [comment]
Since 2024-01-31, arch-update auto check does not trigger anymore. (Despite a reboot on the 4th of February), and manually restarting arch-update services with `systemctl` has no effect either.

I commented all lines in the override.conf and restarted again arch-update services : suddenly it works again.
So for now I'll revert to edit directly `/usr/lib/systemd/user/arch-update.timer` instead of using the override.conf.

**Comment by Antiz96** [comment]
Hi,

I can't reproduce the issue on my side, everything seems to work as intended:

--> With default config
```
$ systemctl --user list-timer
NEXT                          LEFT    LAST                        PASSED    UNIT                 
Sun 2024-02-11 17:58:26 CET **27min** Sun 2024-02-11 16:58:26 CET 32min ago arch-update.timer
```

--> Creating the override config
```
$ systemctl --user edit arch-update.timer
### Editing /home/antiz/.config/systemd/user/arch-update.timer.d/override.conf
### Anything between here and the comment below will become the contents of the drop-in file

[Timer] # I'm adding those three lines
OnUnitActiveSec=
OnUnitActiveSec=1d

### Edits below this comment will be discarded


### /usr/lib/systemd/user/arch-update.timer
# [Unit]
# Description=Run arch-update auto check at boot and then every hour
#
# [Timer]
# OnStartupSec=15
# OnUnitActiveSec=1h
#
# [Install]
# WantedBy=timers.target
```
> Successfully installed edited file '/home/antiz/.config/systemd/user/arch-update.timer.d/override.conf'.

```
$ cat /home/antiz/.config/systemd/user/arch-update.timer.d/override.conf
[Timer]
OnUnitActiveSec=
OnUnitActiveSec=1d
```

--> Relisting timer with override.conf

```
$ systemctl --user list-timer
NEXT                          LEFT    LAST                        PASSED    UNIT       
Mon 2024-02-12 16:58:26 CET   **23h** Sun 2024-02-11 16:58:26 CET 33min ago arch-update.timer       arch-update.service
```

I can only assume your override.conf is wrong somehow... Can you post the output of the following command?
`ls -l ~/.config/systemd/user/arch-update.timer.d/override.conf && cat ~/.config/systemd/user/arch-update.timer.d/override.conf`

**Comment by Saroumane** [comment]
After the latest arch-update (to v1.12) my edit got erased, so I gave another try to the override method.

I followed *exactly* your steps (by the way it is "`list-timers`" with an 's' I think) and in the end, it still does not work : the "LEFT" timing is not changed. (it's in minutes instead of "23h" )

After that, I even tried ` systemctl --user daemon-reload`  and some stop/start commands : no change. (It restart with 1hour left instead of 24h)

As requested : 
```
$ ls -l ~/.config/systemd/user/arch-update.timer.d/override.conf && cat ~/.config/systemd/user/arch-update.timer.d/override.conf
-rw-r--r-- 1 user user 75 Feb 27 22:13 /home/user/.config/systemd/user/arch-update.timer.d/override.conf
[Timer] # I'm adding those three lines
OnUnitActiveSec=
OnUnitActiveSec=1d
```

**Comment by Antiz96** [comment]
> After the latest arch-update (to v1.12) my edit got erased, so I gave another try to the override method.

This is expected, hence why I recommend the proper `systemctl --user edit arch-update.timer` method now.
> 
> I followed _exactly_ your steps (by the way it is "`list-timers`" with an 's' I think) and in the end, it still does not work : the "LEFT" timing is not changed. (it's in minutes instead of "23h" )

It's indeed "list-timer**s**", I probably failed my copy/paste when writing my comment. Edited ;)
> 
> After that, I even tried ` systemctl --user daemon-reload` and some stop/start commands : no change. (It restart with 1hour left instead of 24h)
> 
This shouldn't be necessary, after creating/editing the file via `systemctl --user edit` it should be done automatically.
> As requested :
> 
> ```
> $ ls -l ~/.config/systemd/user/arch-update.timer.d/override.conf && cat ~/.config/systemd/user/arch-update.timer.d/override.conf
> -rw-r--r-- 1 user user 75 Feb 27 22:13 /home/user/.config/systemd/user/arch-update.timer.d/override.conf
> [Timer] # I'm adding those three lines
> OnUnitActiveSec=
> OnUnitActiveSec=1d
> ```

The "# I'm adding those three lines" comment was informative, you're not supposed to actually put it in your override.conf file. As you can see in my previous comment, it's not present when I `cat` the file. Sorry if it wasn't clear...

Run `systemctl --user edit arch-update.timer` again to edit the file and remove the comment so the file looks like this:

```
[Timer]
OnUnitActiveSec=
OnUnitActiveSec=1d
```

That should solve the issue (you can confirm with `systemctl --user list-timers`).

**Comment by Saroumane** [comment]
Yes I know my 'fix' was supposed to be overriden with an arch-update update, you already explained that in a previous comment.
I was just giving some context, and explained why I waited to try again the override method :)

Regarding the remaining problem, I understand that starting a comment in the middle of a line, is not supported in the override file.
So I'll try without and post the results here.
Sorry for not having spotted _all_ the traps you left for me 😉
Joking aside, it's still a great tool, and thanks for helping me.

**Comment by Antiz96** [comment]
> Sorry for not having spotted all the traps you left for me 😉

Haha, my bad. I get it wasn't so clear, I edited my initial comment to make it clearer.
But yeah, removing the comment should fix the issue :)

> Joking aside, it's still a great tool, and thanks for helping me.

My pleasure! Thanks for the kind words <3
